# ncrmro-workstation — Dell U5226KW and centered master layout.
monitor=desc:Dell Inc. DELL U5226KW 9XM3884, 6144x2560@120.00, 0x0, 1.00, transform, 0

master {
  new_status=slave
  orientation=center
  slave_count_for_center_master=0
}

exec-once=env KEYSTONE_AUDIO_DEFAULT_SINK='alsa_output.usb-Loud_Technologies_Inc._Onyx_Blackjack-00.analog-stereo' KEYSTONE_AUDIO_DEFAULT_SOURCE='alsa_input.usb-046d_Logitech_BRIO_873172C7-03.analog-stereo' keystone-audio-menu apply-config-defaults
exec-once=env KEYSTONE_PRINTER_DEFAULT='Brother_HL_L2395DW_series' keystone-printer-menu apply-config-defaults
