source=/home/ncrmro/.config/keystone/current/theme/hyprlock.conf
auth {
  fingerprint {
    enabled=true
  }
}

background {
  monitor=
  blur_passes=3
  brightness=0.500000
  path=/home/ncrmro/.config/keystone/current/background
}

general {
  disable_loading_bar=true
  no_fade_in=false
}

input-field {
  monitor=
  size=600, 100
  check_color=$check_color
  fade_on_empty=false
  fail_text=Wrong ($ATTEMPTS)
  font_color=$font_color
  font_family=JetBrainsMono Nerd Font
  font_size=32
  halign=center
  inner_color=$inner_color
  outer_color=$outer_color
  outline_thickness=4
  placeholder_color=$placeholder_color
  placeholder_text=  Enter Password
  position=0, 0
  rounding=0
  shadow_passes=0
  valign=center
}

label {
  monitor=
  color=$font_color
  font_family=JetBrainsMono Nerd Font
  font_size=24
  halign=center
  position=0, -100
  text=$FPRINTPROMPT
  text_align=center
  valign=center
}
