typeset -U path cdpath fpath manpath
for profile in ${(z)NIX_PROFILES}; do
  fpath+=($profile/share/zsh/site-functions $profile/share/zsh/$ZSH_VERSION/functions $profile/share/zsh/vendor-completions)
done

HELPDIR="/run/current-system/sw/share/zsh/$ZSH_VERSION/help"

source "/etc/profiles/per-user/$USER/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"
ZSH_AUTOSUGGEST_STRATEGY=(history)


# oh-my-zsh extra settings for plugins

# oh-my-zsh configuration generated by NixOS
plugins=(git colored-man-pages)

ZSH_THEME="robbyrussell"
source $ZSH/oh-my-zsh.sh

eval "$(zoxide init zsh )"

# History options should be set in .zshrc and after oh-my-zsh sourcing.
# See https://github.com/nix-community/home-manager/issues/177.
HISTSIZE="100000"
SAVEHIST="100000"

HISTFILE="/home/ncrmro/.zsh_history"
mkdir -p "$(dirname "$HISTFILE")"

setopt HIST_FCNTL_LOCK

# Enabled history options
enabled_opts=(
  HIST_IGNORE_DUPS HIST_IGNORE_SPACE SHARE_HISTORY
)
for opt in "${enabled_opts[@]}"; do
  setopt "$opt"
done
unset opt enabled_opts

# Disabled history options
disabled_opts=(
  APPEND_HISTORY EXTENDED_HISTORY HIST_EXPIRE_DUPS_FIRST HIST_FIND_NO_DUPS
  HIST_IGNORE_ALL_DUPS HIST_SAVE_NO_DUPS
)
for opt in "${disabled_opts[@]}"; do
  unsetopt "$opt"
done
unset opt disabled_opts

if [[ $options[zle] = on ]]; then
  source <(fzf --zsh)
fi

_keystone_zellij_effective_cwd() {
  local cwd="${PWD:-$HOME}"

  if [[ -z "$cwd" || ! -d "$cwd" ]]; then
    cwd="$HOME"
  fi

  print -r -- "$cwd"
}

_keystone_zellij_pipe_tab_name() {
  [[ -n "${ZELLIJ:-}" && -n "${ZELLIJ_PANE_ID:-}" ]] || return 1

  local title="$1"
  local payload
  payload="$(jq -nc \
    --arg pane_id "$ZELLIJ_PANE_ID" \
    --arg name "$title" \
    '{ pane_id: $pane_id, name: $name }')"

  zellij action pipe \
    --plugin "file:/etc/profiles/per-user/$USER/share/zellij/plugins/zellij-tab-name.wasm" \
    --name change-tab-name \
    -- "$payload" >/dev/null 2>&1
}

ztab() {
  if [[ $# -eq 0 ]]; then
    print "usage: ztab <name>" >&2
    return 1
  fi

  _keystone_zellij_pipe_tab_name "$*"
}

znewtab() {
  local title="$*"
  local tab_cwd
  tab_cwd="$(_keystone_zellij_effective_cwd)"

  if [[ -n "$title" ]]; then
    timeout 5s \
      zellij action new-tab --cwd "$tab_cwd" --name "$title"
  else
    zellij run \
      --floating \
      --close-on-exit \
      --cwd "$tab_cwd" \
      -- "keystone-zellij-new-tab-prompt"
  fi
}

if [ -f /run/agenix/ncrmro-immich-api-key ]; then
  export IMMICH_API_KEY="$(tr -d '\n' < /run/agenix/ncrmro-immich-api-key)"
fi

# Local Ollama coding-harness wrappers: run the llm-agents CLIs against
# $OLLAMA_HOST with the fleet-configured model. Hosted `claude` /
# `opencode` are unchanged.
claude-local() {
  ANTHROPIC_BASE_URL="$OLLAMA_HOST" ANTHROPIC_AUTH_TOKEN="ollama" \
    claude --model qwen3:32b "$@"
}
opencode-local() {
  OPENCODE_PROVIDER="ollama" OPENCODE_MODEL="qwen3:32b" \
    opencode "$@"
}

if [[ $TERM != "dumb" ]]; then
  eval "$(starship init zsh)"
fi

source "/etc/profiles/per-user/$USER/etc/profile.d/command-not-found.sh"

lg() {
    export LAZYGIT_NEW_DIR_FILE=~/.lazygit/newdir
    command lazygit "$@"
    if [ -f $LAZYGIT_NEW_DIR_FILE ]; then
      cd "$(cat $LAZYGIT_NEW_DIR_FILE)"
      rm -f $LAZYGIT_NEW_DIR_FILE > /dev/null
    fi
}

if [[ -n $GHOSTTY_RESOURCES_DIR ]]; then
  source "$GHOSTTY_RESOURCES_DIR"/shell-integration/zsh/ghostty-integration
fi

eval "$(direnv hook zsh)"

# NixOS rebuild helper with --boot support for boot-critical changes.
update() {
  local host
  local cmd="switch"
  host="$(hostname)"
  if [[ "$1" == "--boot" ]]; then
    cmd="boot"
    shift
  fi
  sudo nixos-rebuild "$cmd" --flake "$HOME/repos/ncrmro/ks-config#$host" "$@"
  if [[ "$cmd" == "boot" ]]; then
    echo "Reboot required to apply changes."
  fi
}

alias -- claude-work='CLAUDE_CONFIG_DIR=~/.claude-work claude'
alias -- dc=docker-compose
alias -- 'docker comppose'=docker-compose
alias -- g=git
alias -- grep=rg
alias -- k=kubectl
alias -- killport='function _killp(){ lsof -nti:$1 | xargs kill -9 };_killp'
alias -- l='eza -1l'
alias -- lg=lazygit
alias -- ls='eza -1l'
alias -- y=yazi
alias -- zs='zesh connect'
alias -- ztab='zellij action rename-tab'
for keystone_fragment in "$HOME/.config/keystone/shell.d"/*.zsh(N); do
  source "$keystone_fragment"
done
unset keystone_fragment
source "/etc/profiles/per-user/$USER/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
ZSH_HIGHLIGHT_HIGHLIGHTERS+=()
